resources:
  - mariadb.yaml
secretGenerator:
  - name: prototype-db
    envs: 
    - .env.secrets
generatorOptions:
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.4.7
    app.kubernetes.io/instance: prototype-db
    app.kubernetes.io/managed-by: Helm
  disableNameSuffixHash: true