apiVersion: v1
kind: Service
metadata:
  name: {{ include "ampsersand.fullname" . }}
  namespace: {{ .Release.Namespace | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "ampsersand.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ampsersand.selectorLabels" . | nindent 4 }}
